import type { NextPage } from 'next';
import Head from 'next/head';
import 'twin.macro';
import Jumbotron from '../components/Contents/Jumbotron';
import AboutMe from '../components/Contents/AboutMe';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main tw="pt-[74px]">
        <Jumbotron />
        <div tw="space-y-[80px]">
          <AboutMe />
        </div>
      </main>
    </div>
  );
};

export default Home;
