/** @jsxImportSource @emotion/react */
import type { NextPage } from 'next';
import Head from 'next/head';
import 'twin.macro';
import Jumbotron from '../components/Contents/Jumbotron';
import AboutMe from '../components/Contents/AboutMe';
import Skills from '../components/Contents/Skills';
import CareerSummary from '../components/Contents/CareerSummary';
import CareerDetail from '../components/Contents/CareerDetail';
import Awards from '../components/Contents/Awards';
import Experiences from '../components/Contents/Experiences';
import Education from '../components/Contents/Education';
import Projects from '../components/Contents/Projects';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>hoondev resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main tw="pt-[74px] pb-[100px]">
        <Jumbotron />
        <div tw="space-y-[80px]">
          <AboutMe />
          <Skills />
          <CareerSummary />
          <CareerDetail />
          <Awards />
          <Experiences />
          <Projects />
          <Education />
        </div>
      </main>
    </div>
  );
};

export default Home;
